site_name: "CPP Proto Builder"
site_url: "https://google.github.io/kokoro-codelab-vmirian/"
repo_name: "CPP Proto Builder"
repo_url: "https://github.com/google/kokoro-codelab-vmirian/"
edit_uri: ""
docs_dir: "docs_src/"
site_dir: "docs/"
theme:
  name: "material"
  features:
    - navigation.expand
nav:
  - Overview: 'home.md'
  - Home: 'home.md'
  - Config: 'config.md'
  
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
